INSERT INTO SPAR_FUND_SRCE_CODE (SPAR_FUND_SRCE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('BCT', 'BC Timber Sales', '2003-04-01', '9999-12-31');
INSERT INTO SPAR_FUND_SRCE_CODE (SPAR_FUND_SRCE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('CBI', 'Carbon Offset Investment', '2013-08-01', '9999-12-31');
INSERT INTO SPAR_FUND_SRCE_CODE (SPAR_FUND_SRCE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('CL', 'Catastrophic Losses', '1905-01-01', '2099-09-30');

-- Not effective yet
INSERT INTO SPAR_FUND_SRCE_CODE (SPAR_FUND_SRCE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('CI', 'Catastrophic Issues', '2033-01-01', '2099-09-30');
-- Expired
INSERT INTO SPAR_FUND_SRCE_CODE (SPAR_FUND_SRCE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('CO', 'Catastrophic Others', '2002-01-01', '2022-09-30');