insert into PARENT_TREE_GENETIC_QUALITY (
  GENETIC_QUALITY_ID,
  PARENT_TREE_ID,
  SEED_PLAN_UNIT_ID,
  GENETIC_TYPE_CODE,
  GENETIC_WORTH_CODE,
  GENETIC_QUALITY_VALUE,
  GENETIC_WORTH_CALC_IND
) VALUES (
  2563,
  4032,
  7,
  'BV',
  'GVO',
  18,
  'Y'
);
